project:
  type: website
  output-dir: docs

website:
  title: "Pranay's Blog"
  site-url: https://pranayvadd.github.io
  navbar:
    background: "#007399"
    foreground: "#FFFFFF"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pranayvadd/
      - icon: linkedin
        href: https://www.linkedin.com/in/pranay-vadd/
format:
  html:
    theme: sandstone
    css: styles.css



